execute @s[tag=!op] ~~~ tellraw @a[tag=notify] {"rawtext":[{"text":"§r§6[§aScythe§6]§r "},{"selector":"@s"},{"text":"'s ender chest was cleared."}]}
tellraw @s[tag=op] {"rawtext":[{"text":"To clear someones ender chest use this command \"/execute [playername] ~~~ function tools/ecwipe\""}]}

replaceitem entity @s[tag=!op] slot.enderchest 0 air
replaceitem entity @s[tag=!op] slot.enderchest 1 air
replaceitem entity @s[tag=!op] slot.enderchest 2 air
replaceitem entity @s[tag=!op] slot.enderchest 3 air
replaceitem entity @s[tag=!op] slot.enderchest 4 air
replaceitem entity @s[tag=!op] slot.enderchest 5 air
replaceitem entity @s[tag=!op] slot.enderchest 6 air
replaceitem entity @s[tag=!op] slot.enderchest 7 air
replaceitem entity @s[tag=!op] slot.enderchest 8 air
replaceitem entity @s[tag=!op] slot.enderchest 9 air
replaceitem entity @s[tag=!op] slot.enderchest 10 air
replaceitem entity @s[tag=!op] slot.enderchest 11 air
replaceitem entity @s[tag=!op] slot.enderchest 12 air
replaceitem entity @s[tag=!op] slot.enderchest 13 air
replaceitem entity @s[tag=!op] slot.enderchest 14 air
replaceitem entity @s[tag=!op] slot.enderchest 15 air
replaceitem entity @s[tag=!op] slot.enderchest 16 air
replaceitem entity @s[tag=!op] slot.enderchest 17 air
replaceitem entity @s[tag=!op] slot.enderchest 18 air
replaceitem entity @s[tag=!op] slot.enderchest 19 air
replaceitem entity @s[tag=!op] slot.enderchest 20 air
replaceitem entity @s[tag=!op] slot.enderchest 21 air
replaceitem entity @s[tag=!op] slot.enderchest 22 air
replaceitem entity @s[tag=!op] slot.enderchest 23 air
replaceitem entity @s[tag=!op] slot.enderchest 24 air
replaceitem entity @s[tag=!op] slot.enderchest 25 air
replaceitem entity @s[tag=!op] slot.enderchest 26 air
replaceitem entity @s[tag=!op] slot.enderchest 27 air
replaceitem entity @s[tag=!op] slot.enderchest 28 air
replaceitem entity @s[tag=!op] slot.enderchest 29 air