scoreboard objectives remove flyvl
scoreboard objectives remove flycheck
scoreboard objectives remove jesusvl
scoreboard objectives remove phasevl
scoreboard objectives remove speedvl
scoreboard objectives remove anglevl
scoreboard objectives remove killauravl
scoreboard objectives remove timer
scoreboard objectives remove aura_timer
scoreboard objectives remove epearlGlitch
scoreboard objectives remove interactusevl
scoreboard objectives remove illegalitemsvl
scoreboard objectives remove leftclick
scoreboard objectives remove leftclickvl
scoreboard objectives remove leftclick_timer
scoreboard objectives remove isBanned
scoreboard objectives remove lastYpos
scoreboard objectives remove currentYpos
gamerule commandblockoutput true
tag @a remove op
tag @a remove flying
tag @a remove vanished
tag @a remove bypass
tag @a remove ban
tag @a remove notify
tag @a remove killauratest
tag @a remove killauratest2
tag @a remove noaura
tag @a remove speedtest
tag @a remove speedtest2
tag @a remove isOnAir
kill @e[type=armor_stand,name=speedtest]
